services:
  postgres:
    image: postgres:16
    container_name: outventura_postgres
    restart: always
    environment:
      POSTGRES_USER: outventura
      POSTGRES_PASSWORD: outventura123
      POSTGRES_DB: outventura_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: outventura_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@outventura.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  backend:
    build: .
    container_name: outventura_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://outventura:outventura123@postgres:5432/outventura_db?schema=public
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: outventura_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data: